### ISSUE TITLE
Cannot read property 'length' of undefined when pageLoading is true

### ISSUE THREAD

**Issue by markgwaps04** [tabalinas/jsgrid#1300]
Uncaught TypeError: Cannot read property 'length' of undefined
    at d._refreshContent (jsgrid.js:7)
    at d.refresh (jsgrid.js:7)
    at d._handleOptionChange (jsgrid.js:7)
    at d.option (jsgrid.js:7)
    at d.finishLoad (jsgrid.js:7)
    at d.<anonymous> (jsgrid.js:7)
    at Object.f (jquery-1.8.0.min.js:2)
    at k (jquery-1.8.0.min.js:2)
    at Object.fireWith (jquery-1.8.0.min.js:2)
    at Object.fire [as resolve] (jquery-1.8.0.min.js:2)

jsGrid config
``  profiling_table.jsGrid({
                    height: "auto",
                    width: "100%",
                    pagerContainer: ".pager",
                    filtering: true,
                    pageLoading : true,
                    inserting: true,
                    editing: true,
                    sorting: true,
                    data: [],
                    css: "scroll",
                    paging: true,
                    autoload: true,
                    pageSize: 10,
                    pageButtonCount: 10,
                    deleteConfirm: "Do you really want to delete client?",

                    onError: param => {
                        document.write(param.args[FIRST_ROW].responseText)
                    },

                    invalidNotify: () => swal('Some field is required to fill', "", "warning"),

                    onItemUpdated: update,

                    onItemEditing: args => setTimeout(function () {
                        update();
                    }, 1),

                    onRefreshing: function (args) {

                        console.log(this);

                        this.onDataLoading(args);
                        update();

                    },
                    onRefreshed: function (args) {
                        this.onDataLoaded(args);
                        update();
                    },

                    onDataLoading : function(args) {
                        this._loadIndicator.show();
                    },

                    onDataLoaded: function(args) {
                        this._loadIndicator.hide();
                    },

                    _createNoDataRow: function () {

                        const totalWidth = Array
                            .from(this.fields)
                            .reduce((current, old) => (current || 0) + old.width, 0);

                        const tableData = $("<td>")
                            .addClass(this.cellClass)
                            .attr("colspan", this.fields.length)
                            .attr("width", totalWidth)
                            .append(this.noDataContent);

                        return $("<tr>")
                            .addClass(this.noDataRowClass)
                            .append(tableData);

                    },

                    get controller() {

                        this.pageLoading = true;

                        const obj = {
                            loadData: function (filter) {

                                console.log(filter);

                                const data = $.Deferred();

                                $.ajax({
                                    type: "POST",
                                    contentType: "application/json; charset=utf-8",
                                    dataType: 'json',
                                    url: "/profiling/ofPopulate",
                                    data: filter,
                                }).done(function (response) {
                                    data.resolve(response);
                                });

                                return data.promise();

                            },
                            insertItem: function (item) {

                                return $.ajax({
                                    type: "POST",
                                    url: "/profiling/ofInsert",
                                    data: item,
                                }).done(function (res) {
                                    profiling_table.jsGrid("loadData");
                                });

                            },
                            updateItem: function (item) {

                                return $.ajax({
                                    type: "POST",
                                    url: "/profiling/ofEdit",
                                    data: item,
                                }).done(function (response) {
                                    profiling_table.jsGrid("loadData");
                                });

                            }
                        };

                        return obj;

                    },

                    fields: [
                        {
                            type: "control",
                            width: 100,
                            css: "fixed_column",
                            deleteButton: false,
                            itemTemplate: function (value, item) {

                                const root = this;

                                const edit = jsGrid
                                    .fields
                                    .control
                                    .prototype
                                    .itemTemplate
                                    .apply(this, arguments);

                                const pending_template = '<label><i class="fa fa-comment"></i></label>';
                                const questionnaire = $(pending_template)
                                    .attr({id: "btn-edit-" + item.id})
                                    .attr({"class": "jsgrid_button-custom text-success"})
                                    .attr({"title": "Household questions"})
                                    .off("click")
                                    .on("click", function (e) {

                                        define_const("OfProfilingId", item.id);

                                        root._grid._loadIndicator.show();

                                        jQuery("#questionaire").load("/profiling/adding/template", function () {

                                            hide_seek_viewport();

                                            const obj = {};
                                            obj["/support/js/my_js/profiling/adding.js?" + random_apha_num()] = "";

                                            require_src(obj);

                                            back_viewport();

                                            root._grid._loadIndicator.hide();

                                        });

                                        e.stopPropagation();

                                    });

                                return $("<div>")
                                    .append(edit)
                                    .append(questionnaire);

                            }
                        },
                        {
                            name: "respondent_name",
                            css: "fixed_column",
                            title: "Respondent Name",
                            type: "text",
                            width: 250,
                            validate: "required"
                        },
                        {
                            name: "date_interview",
                            title: "Date of Interview",
                            css: "fixed_column",
                            type: "text",
                            width: 200,
                            placeholder: "Test",
                            editing: false,
                            validate: "required"
                        },
                        {
                            name: "province",
                            title: "Province",
                            type: "text",
                            width: 250,
                        },
                        {name: "city_municipality", title: "City/Municipality", type: "text", width: 200},
                        {name: "barangay", title: "Barangay", type: "text", width: 200},
                        {name: "zone", title: "Zone", type: "text", width: 150},
                        {name: "purok_sitio", title: "Purok/Sitio", type: "text", width: 150},
                        {name: "street", title: "Street", type: "text", width: 150},
                        {name: "house_number", title: "House Number", type: "text", width: 150},
                        {
                            name: "household_number",
                            title: "House hold identification number",
                            type: "text",
                            width: 150,
                        },
                        {
                            name: "latitude",
                            title: "Latitude",
                            type: "text",
                            width: 150,
                            editing: false,
                            inserting: false
                        },
                        {
                            name: "longtitude",
                            title: "Longtitude",
                            type: "text",
                            width: 150,
                            editing: false,
                            inserting: false
                        }
                    ]

                });

**Comment by markgwaps04** [comment]
![image](https://user-images.githubusercontent.com/32358422/67443606-16a4a080-f638-11e9-999a-34f538f489c4.png)

**Comment by apolinux** [comment]
I have the same error using pageLoading true too. Please some one fix this problem.

**Comment by apolinux** [comment]
I think it is resolved returning the $.ajax value directly.

**Comment by markgwaps04** [comment]
I just realize that i need to return an object that has data and itemCount property 

```
 const table = jq(".student_list").jsGrid({
        ......
        autoload : true,
        paging: true,
        pageLoading: true,
        pageIndex: 0,
        pageSize: 3,


        width: "100%",
        controller: {
            loadData: function (args) {

                console.log(args);

                const deferred = $.Deferred();

                jq.ajax({
                    url: '/students/student_list',
                    dataType: 'json',
                    error: e => console.log(e.responseText),
                    success: function (data) {

                        let chunk = lodash.chunk(data, 2);

                        chunk = chunk.map(function (per) {
                            return {
                                col1: per[0],
                                col2: per[1] || null
                            }
                        });

                       /** @required **/

                        deferred.resolve({
                            data : chunk,
                            itemsCount : chunk.length
                        });

                    }
                });

                return deferred.promise();
            }
        },

        fields: [
            {
                name: "col1",
                headercss: "hide",
                itemTemplate: colRenderer,
            },
            {
                name: "col2",
                headercss: "hide",
                itemTemplate: colRenderer,
            },
        ]
    });
```

@apolinux returning the ajax object directly does not solved the problem but anyway thanks
